### ISSUE TITLE
elements-angular: Evaluate standalone mode

### ISSUE THREAD

**Issue by janivo** [inovex/elements#1078]
### Description
Angular now offers a standalone components approach as an alternative to the NgModule approach. Evaluate the feasibility and benefits of transitioning our Angular components to this new standalone format. 

### Key Considerations:
  - Assess the advantages of adopting standalone components in terms of development workflow, maintainability, and potential performance improvements.
  - Evaluate how the standalone components approach enhances the experience for consumers of our Angular components. Consider factors such as ease of integration, reduced dependencies, and improved flexibility.
  - Investigate whether Stencil, our component compiler, provides a seamless way to export components as standalone
  - Will our current `InoElementsConfig` still work with this new approach?

### Acceptance Criteria

- Provide a comprehensive report summarizing the benefits and drawbacks of adopting standalone components in Angular.
- Formulate a clear recommendation on whether to transition to standalone components based on the evaluation.
- If recommended, outline the steps and considerations for implementing standalone components. This should include any necessary updates to our Angular and Stencil configurations.

**Comment by BenPag** [comment]
### Evaluation of providing standalone mode for Angular
- Stencil provides an export mode for standalone components
  - requires additional output target: `dist-custom-elements` 
- `InoElementsConfig` is supported but needs an extra provider export
- Required a copy of all `@Directive` to set the `standalone` property
  - To reduce code duplications we can add a mew layer for shared code
- The behavior of assets loading like icons changed
  - assets not copied to output automatically
  - assets loaded dynamically via assets path
  - might be a problem when integrate it

Beside this. when we provide this new approach following things we have to update:
- Our integration guide
- Add a migration guide to standalone mode
  - Mostly we can adapt from [Ionic Framework](https://ionicframework.com/docs/angular/build-options#migrating-from-modules-to-standalone)

Draft PR for implementing standalone mode: https://github.com/inovex/elements/pull/1242

**Comment by janivo** [comment]
see resulted task in #1274 and #1274
