### ISSUE TITLE
Landingpage: Re-Evaluate internationalisation

### ISSUE THREAD

**Issue by janivo** [inovex/elements#1092]
## Context
On the landing page, we had to introduce a concept for translation that does not use Next.js on-board resources, since we don't have these available in a static export.

This concept worked previously but feels a bit wonky now. Symptoms are for example that we get to a 404 page when refreshing a page or the first set language is always German. Also, it is difficult in development to change a path without giving any information about the current locale.

## To Do 
See if there are any possibilities to use the default board means provided by Next.js or if there are other widely used approaches to implement internationalisation with Next.js and static export.

**Comment by BenPag** [comment]
In fact that we´re using the Next,js **pages router** and `next export` command no build-in support for i18n is provided. 

To support i18n with pages router there some libraries which we can use:
- https://github.com/Yrobot/i18next-ssg 
- https://github.com/martinkr/next-export-i18n

But when we switch to the **app router** concept of Next.js then I think we can use there build-in resources described here:
https://nextjs.org/docs/app/building-your-application/routing/internationalization

Next.js provides an example for that here: https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing
I checked it out, created a `next.config.js` file with `output: export` setting and run the `next build` command. As result I get an out dir with follwoing content:

![image](https://github.com/inovex/elements/assets/23154336/0c6d602d-9d50-4407-bb00-e7355564cca7)

**Comment by janivo** [comment]
see resulted task in #1272
