### ISSUE TITLE
Ui-Patterns: Settings Page

### ISSUE THREAD

**Issue by janivo** [inovex/elements#1126]
### Description
We aim to improve our UI-Library by introducing a new example pattern – a settings page. This pattern will serve as a practical and reusable template for developers utilizing our library. The settings page should cover various components commonly found in web application settings, with HTML and Tailwind snippets for easy integration.

### Acceptance Criteria
- **Design**
  - Collaborate with the design team to create a visually appealing and user-friendly settings page layout.
  - Ensure the design adheres to our UI-Library's established design system.

- **Development**
  - Generate HTML code for the settings page
  - Add a dedicated section for the new pattern to our landingpage

### Examples

![Image](https://github.com/inovex/elements/assets/22963121/325046cd-0aae-449a-9996-3bb54d62d47a)

**Comment by MBuchberger** [comment]
The Design is now finally ready for implementation. 
You can find it [here](https://www.figma.com/file/fsZi5iM8qbCOpZxypPxbi8/inovex-Elements-Design-System?type=design&node-id=2509%3A2604&mode=design&t=rN1EpHsOmd4x1dYQ-1)

![Image](https://github.com/inovex/elements/assets/117914010/e7f0e52b-89e3-4b82-9cb3-4cdae28776d3)
