### ISSUE TITLE
ino-accordion: `max-height` is too low

### ISSUE THREAD

**Issue by janivo** [inovex/elements#1161]
## Description
As reported in Slack, the current `max-height` setting in the `ino-accordion` component is causing issues when displaying larger content. The current value of `1000px` appears to be too restrictive in certain cases. While a `max-height` is necessary for the animation to work, there is a proposal to increase this value to a much higher one, such as `99999px`, to accommodate larger content.

## Steps to Reproduce

1. Add larger content to the `ino-accordion`.
2. Observe that the content is truncated due to the current `max-height` of `1000px`.

## Expected Behavior
The `max-height` in the `ino-accordion` component should be set to a value that allows for the proper display of larger content without unnecessary truncation.

## Actual Behavior
The current `max-height` of `1000px` restricts the display of larger content within the `ino-accordion`, leading to undesired truncation.

## Acceptance Criteria

- Update the `max-height` property in the `ino-accordion` component to a higher value, such as `99999px`.
- Ensure that the updated `max-height` accommodates larger content without causing visual issues or truncation.
- Conduct thorough testing to confirm that the adjustment does not negatively impact the component's functionality or animation.

**Comment by TobiasHeimGalindo** [comment]
After checking the ino-accordion component, we actually don't use a max-height in our current version (v9.0.0). Instead, we've [transitioned to a height: auto configuration with a CSS grid](https://keithjgrant.com/posts/2023/04/transitioning-to-height-auto/#with-grid). Tests with a 3000-word placeholder text confirmed that large content is accommodated without clipping. This issue stems from an older version of the elements (pre v9.0.0).
