### ISSUE TITLE
Refactor fonts

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#160]
As a consumer, I would like to have the choice of my preferred font. Currently, the use of Lato font is deeply connected inside the elements and wrappers like Angular.

It would be better to let the consumer decide whether the fonts should be imported or not.

### Aspects of a possible solution

* The default font face for all components can be changed at a single place (css variable?)
* No inovex-elements fonts are imported if the consumer changes the font face.
* No font-dependant code in any angular/react wrapper.

**Comment by janivo** [comment]
@silentHoo you told me that we host our fonts on the inovex servers now. Could you provide a url?

This makes it much easier to import the fonts and we could revert our changes made in https://github.com/inovex/elements/pull/61 and https://github.com/inovex/elements/pull/82

**Comment by silentHoo** [comment]
The implementation is now done. I'll priorize this issue higher.

**Comment by silentHoo** [comment]
**Possible solutions**:

* Revert changes made in #61 and #82.
* Use the static inovex host (https://static.inovex.de/css/lato.css) for font loading.
* Global CSS Variable containing the `font-family` value.
