### ISSUE TITLE
Remove constants.ts in ino-button and ino-segment-button

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#161]
Currently, the `ino-button` and `ino-segment-button` have css classes defined in separate `constant.ts` files. This was an approach to provide more clarity within the component files.

However, in my opinion, this leads to less transparency. Further, all components should handle constants in the same way, i.e. either all css classes in constant files or none.

### Possible solution
Delete `constant.ts` in the respective components and move the css classes to the components again.

**Comment by P1NHE4D** [comment]
I agree - it's rather pointless to have a separate `constant.ts` file for just two components. I'm working on it.
