### ISSUE TITLE
ino-progress-bar: Buffering dots not working

### ISSUE THREAD

**Issue by janivo** [inovex/elements#177]
### Describe the bug
The buffering dots of the `ino-progess-bar` are not displayed anymore. This bug was introduced with version 2.0.0.

### To Reproduce
1. Start the Storybook
2. Go to Notification/ino-progess-bar
3. See variants without buffering dots

### Screenshots
Version 1.2.0:
![image](https://user-images.githubusercontent.com/22963121/98538500-2286f300-228b-11eb-9962-2439892a9657.png)

Latest:
![image](https://user-images.githubusercontent.com/22963121/98538530-2fa3e200-228b-11eb-8690-aeebfb7a4504.png)

### Possible Solution
This was probably introduced with the MDC update to version 7.0.0. Maybe it's just a class that's missing.

**Comment by P1NHE4D** [comment]
It seems like this bug has its roots in the mdc library as neither the class names nor the parameter names changed. I also checked the changelog for any breaking changes to the `mdc-linear-progress` component that may explain the absence of the buffering dots. Sadly, I couldn't find anything related to the issue. 
According to the documentation, there were some slight changes to the stylesheet imports, but changing them did not have any effect whatsoever. Disabling the shadow dom did not work either.

**Comment by P1NHE4D** [comment]
I would like to add that I observed that the value of the `buffer` was set to undefined after setting it to a numeric value. Conversely, the `buffer` parameter of the underlying MDCFoundation component was set to the correct value.
