### ISSUE TITLE
Add documentation how CSS Custom Property handling internally works

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#194]
We need to clarify the CSS Custom Property (aka CSS Variables) handling within the elements. It's confusing as we use a mix of built-time and run-time logic as well as default values.

The description should be targeted mainly towards contributors, but it's also important for developers working with the elements to have a solid understanding how CSS Custom properties are processed internally.

Necessary points we need to do:

- Add a new entry **CSS Variables** within the _Doc_ section in Storybook.
- Describe the advantages of using CSS Custom Properties.
- Describe the possibilities for the developer point of view.
- Describe the possibilities for the contributor point of view.
- Add some CSS examples for two or three components for a developer using the elements.

**Comment by janivo** [comment]
should be documented in [our developer docs](https://elements.inovex.de/version/v7.1.0/?path=/docs/docs-contributing-developing-components--page)
