### ISSUE TITLE
ino-monthpicker: Skipping next and previous years on arrow click

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#215]
### Describe the bug

When navigating through years by clicking the arrow icons, a click will either jump over multiple previous or next years. Sometimes another month is marked as well.

### To Reproduce

![buggyMonthpicker(1)](https://user-images.githubusercontent.com/1610894/100455752-8b5dd000-30bf-11eb-97b8-34c5bf4acfae.gif)

**Comment by janivo** [comment]
There are some issues with the flatpickr library. See these issues:
- https://github.com/flatpickr/flatpickr/issues/2074
- https://github.com/flatpickr/flatpickr/issues/2236
- https://github.com/flatpickr/flatpickr/issues/2138

What I tried:
- Updating to the latest flatpickr version (4.6.6)
- Suppressing the event handlers of the arrows
- Replacing the year change arrows

There was no way to continuously disable the arrow change handlers. As soon as a valid date was selected and the month-picker was reopened to select another date, the bugs occurred again.

**Comment by silentHoo** [comment]
This ticket is related to https://github.com/inovex/elements/issues/257 and maybe fixes this bug.

**Comment by silentHoo** [comment]
Closed due to merged PR.
