### ISSUE TITLE
ino-monthpicker: Entered user value is either invalid or not the value the user typed in

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#216]
### Describe the bug

When entering a date manually the date input will either be invalid or the value is not the value the user typed in.

### To Reproduce

![buggyMonthpicker(2)](https://user-images.githubusercontent.com/1610894/100455632-4c2f7f00-30bf-11eb-9223-920bc74268bc.gif)

**Comment by janivo** [comment]
This should be fixed with https://github.com/inovex/elements/pull/226

Feel free to reopen this issue if the problem persists.
