### ISSUE TITLE
ino-fab: Replace ino-icon property with ino-icon slot

### ISSUE THREAD

**Issue by P1NHE4D** [inovex/elements#222]
### Describe the solution you'd like
For the sake of consistency, I would like to propose to replace the `inoIcon` property of the the `ino-fab` component with a `ino-icon` slot. However, feel free to share your opinion.

#### AC:

- [x]  The `inoIcon` property of the `ino-fab` component has been removed
- [x] A new `ino-icon` slot has been added to the `ino-fab` component

**Comment by janivo** [comment]
The `inoIcon` prop should not be removed but instead, marked as deprecated.
See the following PR for reference on how to approach this: https://github.com/inovex/elements/pull/189
