### ISSUE TITLE
Refactor datepicker

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#257]
The datepicker is pretty blown up and should be refactored for better code maintainability and readability.

## Some ideas
Think of which part may be better in separated files. For instance, the entire *Type-Specific options* could easily be moved to a `type-specific-options.ts`. Furthermore, the logic of how to validate the field could be moved to a `validation.ts`.

**Comment by silentHoo** [comment]
We can take this idea further and refactor the whole code into separate components for each specific use case to keep it even simpler.

**Comment by silentHoo** [comment]
We will refactor the datepicker and also restyle the design to meet the elements CI.
