### ISSUE TITLE
Update example React project to current release

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#314]
- Add each component of the Storybook Showcase* to the example React project (https://github.com/inovex/elements-example-react)

* https://elements.inovex.de/dist/latest/storybook/?path=/story/docs-showcase--components

**Comment by lschwall** [comment]
I am going to work on this now

**Comment by lschwall** [comment]
anything special that I need to know before adding these components into the page?

**Comment by silentHoo** [comment]
Hi and welcome @lschwall 👋 
Nice to see that you're interested in this project. @janivo already started updating the Vue project (https://github.com/inovex/elements/issues/261). @janivo: Which component variants are you plan to implement in the sample project? I would suggest that one variant for a single component is sufficient.

**Comment by janivo** [comment]
Hi! 

No, there is nothing specific you need to know. Just follow the pattern (define a route, implement the component) and you are good to go. The goal is to show a working react example for every component. So you can just go ahead and pick a component from [our core project](https://elements.inovex.de/dist/latest/storybook/?path=/story/docs-home--welcome).

If you find any errors or outdated documentation while doing so, just open an issue in this repository.

**Comment by lschwall** [comment]
Hey no problem! Thanks so much for getting back. Ill see if I can't get the react components implemented!

**Comment by silentHoo** [comment]
https://github.com/inovex/elements-example-react/pull/31
