### ISSUE TITLE
Update example Angular project to current release

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#315]
- Add each component of the Storybook Showcase[1] to the example Angular project (https://github.com/inovex/elements-example-angular).
- Each component should be on its own page (this simplifies the process of creating a reproduction step with Codesandbox

* [1] https://elements.inovex.de/dist/latest/storybook/?path=/story/docs-showcase--components

**Comment by P1NHE4D** [comment]
- [ ] `ino-button`
- [ ] `ino-card`
- [ ] `ino-carousel`
- [ ] `ino-checkbox`
- [ ] `ino-chip`
- [ ] `ino-chip-set`
- [ ] `ino-datepicker`
- [ ] `ino-dialog`
- [ ] `ino-fab`
- [ ] `ino-fab-set`
- [ ] `ino-header`
- [ ] `ino-icon`
- [ ] `ino-icon-button`
- [ ] `ino-img`
- [ ] `ino-img-list`
- [ ] `ino-input`
- [ ] `ino-input-file`
- [ ] `ino-label`
- [ ] `ino-list`
- [ ] `ino-list-item`
- [ ] `ino-menu`
- [ ] `ino-nav-drawer`
- [ ] `ino-popover`
- [ ] `ino-progress-bar`
- [ ] `ino-radio`
- [ ] `ino-range`
- [ ] `ino-segment-button`
- [ ] `ino-segment-group`
- [ ] `ino-select`
- [ ] `ino-sidebar`
- [ ] `ino-snackbar`
- [ ] `ino-spinner`
- [ ] `ino-switch`
- [ ] `ino-tab`
- [ ] `ino-tab-bar`
- [ ] `ino-table`
- [ ] `ino-textarea`
- [ ] `ino-tooltip`
