### ISSUE TITLE
Match colors and typo to the design

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#320]
**Acceptance criteria**
* Colors and typography of all components correspond to the design.
* Create tasks in the backlog for each component where the implementation deviates from the design specification.

PS: See also ELEMENTS-536 in Jira with further links.

**Comment by pfecht** [comment]
@silentHoo do we still need this one or can we close it in favor of more specific issues?

**Comment by silentHoo** [comment]
Yep, we still need this. Magda is reviewing all the colors across the components and will give an update on that as soon as she has some updates on this.

**Comment by MBuchberger** [comment]
#859
