### ISSUE TITLE
New component: ino-link

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#323]
As an inovex-elements user I have the need to have a link component available. I have added a link in 2 places when building the elements landing page, which looks like a button from the styling. Without a link component, I am forced to use incorrect HTML semantics (an <a> tag around the <ino-button>).

For this reason, a link component that renders an <a> tag but allows styling of the ino-button (with a variant property) among other things would be ideal.
 
**Acceptance Criteria**
* Link component renders button in the design of a link (see also Bootstrap Button Link).

**Comment by janivo** [comment]
No need as the button supports `<a>` elements in its slot. Alternatively, the native `<a>` element can be used as it is styled by our own stylesheet: https://github.com/inovex/elements/blob/c1279b64867ae3c2834715edf9c4f201913c87f2/packages/elements/src/global/styles.scss#L8-L13
