### ISSUE TITLE
ino-datepicker: ino-default-date is not working.

### ISSUE THREAD

**Issue by Sl1nd** [inovex/elements#340]
### Describe the bug

Currently the `ino-default-date` is not working. The default date is always set to current date.

### To Reproduce

1. Go to https://elements.inovex.de/dist/latest/storybook/?path=/story/input-ino-datepicker--default-usage
2. Change `ino-default-date` in "Date Config" Tab

### Your Environment

| Software            | Version |
| ------------------- | ------- |
| @inovex.de/elements | v2.3.0
| Browser             |  Chrome
| Operating System    | MacOS

### Possible Solution

`ino-default-date` property is not  used to configure flatpicker

**Comment by Sl1nd** [comment]
Not fixed for all types. e.g. datetime, month

**Comment by janivo** [comment]
We need to think about weather the `defaultDate`, `defaultMinute` and `defaultHour` props still make sense as our datepicker is now uncontrolled.

I would suggest:
- [ ] Removing the props mentioned above
- [ ] Use `value` as the default date if exists  
- [ ] The datepicker popover should open in the correct month (e.g. `value="09.07.2021"` should open in July 2021)

**Comment by janivo** [comment]
I decided to keep the default props (`ino-default-date`, `ino-default-hour`, ...) because there might be some cases where it's useful e.g.:
If you want to "suggest" a date to the user without actually pre-selecting a value.
