### ISSUE TITLE
Automate svg and image processing

### ISSUE THREAD

**Issue by JCofman** [inovex/elements#350]
### Is your feature request related to a problem? Please describe.

Manually optimizing SVG and images is an annoying problem and also something we as a developer could easily forget. Therefore I want to suggest adding an automated script to optimize static assets at build time.

### Describe the solution you'd like

There are several helper libraries available. I think we could integrate one of those into our build process.

- https://github.com/svg/svgo
- https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli 
- https://github.com/imagemin/imagemin

**Comment by silentHoo** [comment]
Aren't there any issues with automatic shrinking of SVGs when there are a lot of layers inside of the SVG? I the past I'd some problems by shrinking it manually with SVGOMG.

**Comment by silentHoo** [comment]
We've discussed the problem and we currently don't have any pain with this. So we close this issue.
