### ISSUE TITLE
ino-select: opened menu doens't close on scroll

### ISSUE THREAD

**Issue by Sl1nd** [inovex/elements#37]
### Describe the bug
If you open the select box and scroll the site the menu is kept open.

### To Reproduce
1. Go to 'https://elements.inovex.de/dist/latest/storybook/?path=/story/input-ino-select--default-usage'
2. Click on any 'ino-select' sample to open the options
3. Scroll down and up

### Expected behavior
According to the behavior of the native select the menu should close on scrolling the page.
Probably its a better option to replace the underlying material select with the native one? As there are further complexities with ino-select, propaply its a better solution to switch to the native select and replace the underlying material select https://github.com/inovex/elements/issues/26?

**Comment by JCofman** [comment]
Hey @Sl1nd 

should we rather disable scrolling while the select menu is open? See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
