### ISSUE TITLE
ino-form-row: Remove component

### ISSUE THREAD

**Issue by janivo** [inovex/elements#373]
### Describe the bug

I'm not sure if the component is used. If so, then we should work on the layout of the component.

### To Reproduce

1. Go to https://elements.inovex.de/dist/latest/storybook/?path=/story/input-ino-form-row--default-usage

### Expected behavior

The label and input to be aligned in a row.

### Screenshots

![image](https://user-images.githubusercontent.com/22963121/118995128-307aa680-b987-11eb-92f1-5812e5e75ade.png)

**Comment by silentHoo** [comment]
We should check if any project is using this component. If no project is using it, we should definitely consider to remove them.

**Comment by janivo** [comment]
Component should be removed as it has no specific use case
