### ISSUE TITLE
elements-angular: New Angular Version 12 not compatible

### ISSUE THREAD

**Issue by janivo** [inovex/elements#374]
### Describe the bug

Angular has recently released a new major version. This new version does not work with our current `elements-angular` package built with Angular V11. 

The following error occurs for each icon when you try to launch the Angular V12 application:
```
./node_modules/@inovex.de/elements/dist/inovex-elements/ino-icon/web.svg:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!-- Generated by IcoMoon.io -->
| <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
| <title>web</title>
```
### To Reproduce

1. Pull https://github.com/janivo/elements-angular-v12-error
2. Run `yarn install`
3. Run `yarn serve`

**Comment by Sl1nd** [comment]
Maybe this happens due to Angular's v12 webpack v5 support
