### ISSUE TITLE
(elements-angular?) ino-sidebar: Error on initialization

### ISSUE THREAD

**Issue by janivo** [inovex/elements#376]
### Describe the bug

See the screenshot below. Happens on initialization in an angular project but has no effects on the functionality of the `ino-sidebar`.

### Screenshots

![image](https://user-images.githubusercontent.com/22963121/119504391-351ad280-bd6c-11eb-8be5-64b39453e908.png)

**Comment by P1NHE4D** [comment]
Seems to be an issue specific to Angular since the error does not occur in storybook.
