### ISSUE TITLE
Update material-components-web to v11.0.0

### ISSUE THREAD

**Issue by P1NHE4D** [inovex/elements#379]
We should update the mdc package to the latest version.

Blocked by #341

**Comment by silentHoo** [comment]
When doing the upgrade we should move into a separate branch (main upgrade branch) and branch from there into more fine grained branches. This reduces complexity and we can work on small chunks. A PR is then mergeable into the upgrade branch.

**Comment by silentHoo** [comment]
As v13 is already released, we close this and upgrade to v13 instead.
