### ISSUE TITLE
Month picker not validating and changing month on manual input

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#398]
#### 1. Month picker validation doesn't work
The datepicker validation does not play well for month pickers. In 

https://github.com/inovex/elements/blob/c9d123ecc19f4ffe1de906645bef6de6310b7c19/packages/elements/src/components/ino-datepicker/picker/MonthPicker.ts#L88

The monthpicker plugin decides to use a month only format if a format with date is provided. However, the validator does not know about this "magic" and invalidates the date. This happens after the first selection of a date, event hough the format ist correct.

#### 2. Month is not updated on manual input
Entering a date manually does update the year, but not the month of the open flatpickr instance.

### Minimal Reproduction
Select a date in the respective story https://elements.inovex.de/dist/latest/storybook/?path=/story/input-ino-datepicker--default-usage

### Expected behavior
The date should be valid. The month should be updated on manual input.

### Possible Solution

* Do we even need a month picker?

**Comment by silentHoo** [comment]
@pfecht Isn't this already fixed? I can't reproduce this behaviour in https://elements.inovex.de/dist/latest/storybook/?path=/docs/input-ino-datepicker--form. Can you re-check?

**Comment by pfecht** [comment]
Seems to be not an issue anymore
