### ISSUE TITLE
Move Landingpage & Storybook to GH Pages

### ISSUE THREAD

**Issue by janivo** [inovex/elements#413]
### Request

At the moment, our landing page is hosted in a separate repository and published from there. In order to unify the whole project and not have to do the hosting ourselves, we should use the possibility of Azure and have our storybook hosted there.

### Description of the proposed solution

- [ ] Create a public (?) repository for the landing page
- [ ] Point the entry point of Azure to the output of the landing page app
- [ ] Adjust the current workflow to load the most recent version of our Storybook to Azure
- [ ] Remove the now unnecessary keys from secrets

**Comment by janivo** [comment]
Questions:
- Do we need the current time machine feature?
  - If so, can this still be achieved with Github Pages?
- Should the landing page be moved to the mono-repo?
- Should we consider another cloud provider (Azure, ...)?

**Comment by silentHoo** [comment]
@pfecht Could you update the current status of this issue?
