### ISSUE TITLE
Create new landing page

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#463]
As a product owner it's necessary to get a general overview. And as a developer it's important to start fast with the elements.

Here's what I propose to include:

- [ ] Design (dogfooding inovex elements)
- [ ] Content **FAQ**
- [ ] Content **History**
- [ ] Content **Team**
- [ ] Content **Contact**
- [ ] Content **Sales**: Trainings, Meetups
- [ ] Content **Resources**: Link to blog articles, case studies, screenshots from Sketch, Stackblitz/Codesandbox Starters  for Web Components, Angular, React and Vue
- [ ] Content **Intro-Video**: 2 Min. - Why are the elements better than XY? What's the goal? Why using a component library like elements?
- [ ] Interactive Playground (Code + Preview)
- [ ] Good examples/templates for composed/arranged components (use of #462)
- [ ] Good demo application in StackBlitz/Codesandbox

**Comment by janivo** [comment]
replaced by our milestone _New Landingpage_
