### ISSUE TITLE
[React] ino-button with type="submit" does not submit pressing enter

### ISSUE THREAD

**Issue by ghost** [inovex/elements#474]
### Bug Report

Pressing enter in this form does not submit the form. This should be possible for form having a button with `type="submit"`

However manually pressing the button does submit the form and a snackbar appears as expected.

### Is this a regression?

Did this behavior use to work in the previous version?

- [x] I don't know
- [ ] Yes, the previous version in which this bug was not present was: `vX.Y.Z`
- [ ] No

### Minimal Reproduction

https://codesandbox.io/s/musing-sea-9bbed

### Expected behavior

The form is submitted and a snackbar appears in top-right.

### Your Environment

| Software            | Version |
| ------------------- | ------- |
| @inovex.de/elements |  5.1.0  |
| Browser             |  brave  |
| Operating System    |  windows 10       |

**Comment by MariaLStefan** [comment]
I couldn't recreate this bug it in the latest version (v7.0.0), seems like it got fixed somewhere along the way.
