### ISSUE TITLE
Activate Shadow-DOM for isolated components

### ISSUE THREAD

**Issue by janivo** [inovex/elements#55]
### Is your feature request related to a problem? Please describe.
As our components have straightforward class names, an issue could arise where the class names of the elements and the consumer may conflict.

### Describe the solution you'd like
The Shadow DOM API allows encapsulating the DOM and the styles of a component. This means that we don't have to worry about the correct scoping of our CSS, nor about our internal DOM being disturbed by anything outside our component. Stencil provides the ability to enable the Shadow DOM for our components. Therefore we should use the Shadow DOM for our non-structured components that function on themselves and do not rely on any slotted elements (e.g. `<ino-button>, <ino-checkbox>, ...).

### Additional context
We've already begun to change our components to the shadow DOM but at that time we encountered some problems which lead to the decision to skip this feature for now. Read about it in [this ADR](https://github.com/inovex/elements/blob/master/doc/adr/cancel_shadow-dom.md).

**Comment by silentHoo** [comment]
This might help: https://meowni.ca/posts/part-theme-explainer/

**Comment by P1NHE4D** [comment]
Since the issue was moved from `backlog` to `won't do`, this issue was closed.
