### ISSUE TITLE
ino-input: onBlur test fails after Stencil upgrade

### ISSUE THREAD

**Issue by janivo** [inovex/elements#56]
### Describe the bug
An onBlur event tests fails after upgrading from Stencil v0.18.0 to v1.4.0.

### To Reproduce
1. Uncomment this test: https://github.com/inovex/elements/blob/45b4e51bae5b6d6a78bcf8a61a11c78072dc326d/packages/elements/src/components/ino-input/ino-input.e2e.ts#L22
2. Start test script with `yarn test`
3. See test failing

### Expected behavior
Test to be successful

### Additional context
(by @P1NHE4D)

We tried:
- Searching for similar issues in Stencil's Github Repo
- Triggering the event with the native `blur()` function
- Upgrading Puppeteer

Maybe a Stencil upgrade will do the trick?

**Comment by silentHoo** [comment]
We do not longer spend any time on this issue, we should instead rewrite the test so find a better solution.
