### ISSUE TITLE
Define vision of how we showcase examples (templates, different frameworks, tutorials)

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#661]
We have many different stories dealing with improvements on how we want to proceed with improving our existing docs and getting started:
* step by step tutorial for each framework
* example projects showcasing the inovex elements
* common web app use-cases which might live inside storybook.

We should prioritize this list and define, how we can minimize the overhead of keeping these different branches up-to-date.

**Comment by janivo** [comment]
As a result of a meeting, we've decided that it might be best to start off with the design of the new elements website. The reason is, that the other content (Guides, Showcases, etc.) is dependent on that new website and how we want to approach them.

**Comment by janivo** [comment]
Resulted in #671
