### ISSUE TITLE
Landingpage: Integrate Storybook as Subpage

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#665]
For our new, we want to integrate the storybook better. This means that we don't have a separate page but the storybook as a subpage. 

In the general setup, the storybook has been integrated via iframe. In this story, we should focus on:

* keep an url of the subpage
* ~~maybe more native integration of the storybook rather than iframe~~
* ~~check if the stories itself in storybook can be without iframe (should be possible for HTML storybooks).~~
* ensure that the **latest** version is used

**Comment by janivo** [comment]
implemented by #896, #897 and #898
