### ISSUE TITLE
Wrong nesting of Example-Projects deployment

### ISSUE THREAD

**Issue by janivo** [inovex/elements#701]
If you have a look at the https://github.com/inovex/elements/tree/gh-pages branch, you can the that the contents of the `example-projects` directory are nested incorrectly.

These lines probably have to be adjusted:
https://github.com/inovex/elements/blob/38d91aee9deaa6006fcbef27dd82e710377893d9/.github/workflows/deploy-example-projects.yml#L40-L41

**Comment by BenPag** [comment]
blocked by #691
