### ISSUE TITLE
elements-angular: Cannot find InoElementsModule

### ISSUE THREAD

**Issue by janivo** [inovex/elements#72]
### Describe the bug
Cannot find `InoElementsModule` in `@inovex.de/elements-angular/`. Before the release of version 1.0.0, it was possible to import the Elements Module with `import { InoElementsModule } from '@inovex.de/elements-angular';`. With the current version, you have to import it with `@inovex.de/elements-angular/src/ino-elements.module` which leads to other typescript  errors.

### To Reproduce
1. Clone the [elements-example-angular](https://github.com/inovex/elements-example-angular) project
2. Update the inovex elements dependency to `@inovex.de/elements-angluar` with version being 1.0.0
3. Change the appearances of `@inovex...` to `@inovex.de...`.
4. `ng serve`
5. See compile error

### Expected behavior
Should compile without any problems.

### Your Environment
 

| Software | Version |
| -------- | ------- |
| @inovex.de/elements | 1.0.0 |

**Comment by P1NHE4D** [comment]
It looks like it's working now

**Comment by janivo** [comment]
Yes, I released Version 1.0.1 so the dist files are correct now. But it still requires to release each package by hand. I want to find a way that automates the release process with a script.

**Comment by janivo** [comment]
I described the problem in https://github.com/inovex/elements/issues/110 and will close this issue for now
