### ISSUE TITLE
elements: Design an accordion component

### ISSUE THREAD

**Issue by janivo** [inovex/elements#797]
For our future FAQ, an Accordion component would be useful allowing questions and answers to be expanded and collapsed.

- Should have a header and a text which is collapsed by default
- There is an intuitive way to expand/collapse the text (e.g. button, clickable surface, ...)
- The expand and collapse actions should be animated

Example: https://mui.com/material-ui/react-accordion/

**Comment by MBuchberger** [comment]
**Style 1 won!** 

**Where to find?**
You'll find in the ino-accordion in the Figma **'Elements Design System'** document which is pinned in the folder **'Design'** at our Elements Slack Channel and integrated in the Landingpage in the Figma **'Elements Landing Page'** document where you can see the behavior of the component.
