### ISSUE TITLE
Investigate how our examples projects can be integrated in our landingpage (3PT)

### ISSUE THREAD

**Issue by janivo** [inovex/elements#811]
- Embed our examples projects
- Check code sandbox tools like
  - Codesandbox
  - Stackblitz
  - Codepen
  - VSCode (via `.` in our Github repo)
 
- It should be embeddable in our landingpage
- It should always be up to date with our current master

**Comment by ninaschlz** [comment]
|Tool|Pro|Contra|
|--|--|--|
|**Codesandbox**|nice UI|buggy, for example ino-dialog not displayed correctly|
||installs dependencies very fast|not compatible with monorepo|
||works with our seperated old projects outside of monorepo (except vue)||
||||
|Links|Monorepo: https://codesandbox.io/embed/github/inovex/elements/tree/master/packages/elements-react-example?fontsize=14&hidenavigation=1&theme=dark| Seperate Repo: https://codesandbox.io/embed/github/inovex/elements-example-react/tree/master?fontsize=14&hidenavigation=1&theme=dark|
||||
|**Stackblitz**|nice UI|very long initialization time|
||works well with monorepo (except angular view is not displayed correctly)|many error messages in console|
|||exhausting setup|
|||does not start automatically if start-script is not named "start" (can be fixed)|
|||some dependencies has to be installed manually (can be fixed)|
|||delete references to other parts of monorepo (can be fixed)|
||||
|Links|Monorepo: https://stackblitz.com/github/inovex/elements/tree/master/packages/elements-react-example| Seperate Repo: https://stackblitz.com/github/inovex/elements-example-react/tree/master|
||||
|**CodePen**|colors are customizable|too "simple" - rather for a few files, for whole projects impractical|
|||no modern UI|
|**JSFiddle**||strange github API with framework and version in url - does not work -> `https://jsfiddle.net/gh/get/{framework}/{version}/{github_tree}`|
|**VSCode**||no preview|
