### ISSUE TITLE
Redesign the ino-select

### ISSUE THREAD

**Issue by janivo** [inovex/elements#909]
Now that the design of the `ino-autocomplete` has been updated, let's take a look at the `ino-select` and try to align its design with that of the `ino-autocomplete`.

**Comment by MBuchberger** [comment]
![Image](https://user-images.githubusercontent.com/117914010/231976774-7dcada2b-c1c9-4938-a6d9-f74255a61c91.png)
![Image](https://user-images.githubusercontent.com/117914010/231976775-c656842e-495b-4c6b-9cc8-54747bc8c559.png)
