### ISSUE TITLE
Create Logo for Social Media Preview

### ISSUE THREAD

**Issue by janivo** [inovex/elements#918]
In Github It is possible to provide an image for the social preview (for times when the link is posted e.g. in social networks). We should create an image that:
- contains the elements logo
- contains an inovex-elements label
- meets the requirements (see below)

## Requirements/Recommendations

- should be at least 640×320px
- should be 1280×640px for best display
- should be .jpg or .png

## Template provided by Github

![Image](https://user-images.githubusercontent.com/22963121/228787025-1a7a4b0c-9f81-43fa-b694-92b827ca94b7.png)

**Comment by subserap** [comment]
![Image](https://user-images.githubusercontent.com/128814713/236168273-d55209bb-38d9-42b0-bdb2-264390b0a279.png)
