### ISSUE TITLE
Design an avatar component

### ISSUE THREAD

**Issue by janivo** [inovex/elements#954]
All of our systems have user integration in some way. Therefore it would be nice to have a streamlined representation of a user with a profile picture.

- It is possible to display the avatar of a user
- If the user has no avatar, the first letters of the first and last name should be displayed

<details><summary>Inspiration</summary>
<p>
This is the representation of myself in one of our systems:
</p>
<img src="https://github.com/inovex/elements/assets/22963121/d18d8214-6c36-4c18-9b0d-688fac47ebb1">
</details>

**Comment by subserap** [comment]
![Image](https://github.com/inovex/elements/assets/128814713/f37ba8e2-7f53-48d9-bd8f-98235f5a1f47)
