### ISSUE TITLE
Design a showcase image

### ISSUE THREAD

**Issue by janivo** [inovex/elements#958]
As part of enhancing the visual representation of inovex Elements, we need a captivating showcase image that provides a comprehensive overview of our web components. This showcase image will serve as a visual representation of our product and will be used in our readme and our landing page.

Acceptance Criteria:

- The showcase image should highlight a selection of our key web components, showcasing their functionalities and versatility.
- The image should have a visually appealing design that aligns with our brand identity, utilizing our brand colors and visual elements.

**Comment by janivo** [comment]
Try to arrange the components like the periodic table



![Image](https://github.com/inovex/elements/assets/22963121/2a5f06ba-855b-4e9e-8b7e-22d0401be6e8)

**Comment by subserap** [comment]
![Image](https://github.com/inovex/elements/assets/128814713/792d3d85-6921-4485-935a-ee7f5833c9e0)
