### ISSUE TITLE
ino-markdown-editor: Link-Button is not working

### ISSUE THREAD

**Issue by janivo** [inovex/elements#981]
## Description
As a user, I want to add a link to a certain text in the `ino-markdown-editor`. 

What I expect:
1. Write a text
2. Select the text where I want to provide a link to
3. Click the link button (🔗)
4. I'm able to somehow provide a link to the selected text passage (usually handled by a popover)

## Current state
We currently got a link button that's missing the functionality above. Here's an example:
![Image](https://user-images.githubusercontent.com/22963121/246139357-98ecf023-9a49-4b85-bd64-b9427c12892c.gif)

## Acceptance criteria:
- The user is able to provide a link by clicking the link icon in the ino-markdown-editor

## More
Draw inspiration from Github, Gitlab, Jira, Gdocs, etc. (anything that has a rich text editor).

**Comment by BingeCode** [comment]
Currently we don't have a toolbar when in `markdown` mode. Is that something we want to implement at some point?

I will implement the modal for the `WYSIWYG` mode.
