### ISSUE TITLE
Design a selection component

### ISSUE THREAD

**Issue by janivo** [inovex/elements#984]
## Description

- A selection component (the name is open to change) is a mix of an autocomplete, a select, and a popover
- It can be opened by clicking or focusing on an element
- The input to search for entries in the list is optional (therefore, it should be possible to just display the list without the input above)
- It should be possible to add a new item if it cannot be found
- The selection can be attached to any element (button, chip, ...) and can be **neglected**
- Have a look at our [ino-autocomplete](https://elements.inovex.de/version/latest/?path=/docs/input-ino-autocomplete--playground) as its quite similar to this one

## Examples 

Here are two examples of a selection component within our INCA app:

![Image](https://user-images.githubusercontent.com/22963121/246156436-0645c239-6c18-4951-819d-8a632c1b03aa.gif)
![Image](https://user-images.githubusercontent.com/22963121/246156996-7244270b-dbd7-4cde-9dc1-4107d295a74a.gif)

**Comment by subserap** [comment]
![Image](https://github.com/inovex/elements/assets/128814713/66602002-67c8-4673-9bbc-4235d921a3c4)
