### ISSUE TITLE
ino-select: Emits event when new value is provided

### ISSUE THREAD

**Issue by janivo** [inovex/elements#986]
### Bug Report

When using the `ino-select` in combination with a form control in Angular, the `valueChange` event is emitted even though the user did not interact with the element. The problem occurs when the `ino-select` receives a new value (via the property `value`) that differs from its previous `value`.

### Is this a regression?

Did this behavior use to work in the previous version?

- [ ] I don't know
- [ ] Yes, the previous version in which this bug was not present was: `vX.Y.Z`
- [x] No

### Minimal Reproduction

1. Render a `ino-select` with a predefined `value` (e.g. `Hamburg`) 
2. Add a listener to the `valueChange` event that prints the event
3. Render a button that updates this value to something else (e.g. `Cologne`)
4. Click the button
5. See that an event is emitted even though the value was changed programmatically and not by user interaction

### Expected behavior

No event should occur as the user did not interact with the element itself. Events should only be emitted if the user selects a new value in the `ino-select`. 

### Additional context

Sounds like a general problem with the `ino-select` but I've only tested it in Angular.

### Possible Solution

The issue might be related to this part of the code:
https://github.com/inovex/elements/blob/367cebc47160023e5a5770bd9a358d970a6a5107/packages/elements/src/components/ino-select/ino-select.tsx#L175-L183

**Comment by TobiasHeimGalindo** [comment]
I've done some additional testing to try and reproduce this issue, both in Angular and React. In both cases, when I clicked the button to change the value programmatically, no `valueChange` event was emitted. This seems to be inconsistent with the bug report, as the expected behavior is for no event to be emitted when the value is changed programmatically, which is exactly what I observed in my testing.

However, I noted that in the source code of our `ino-select` component  the `handleInput` function emits a valueChange event **only** if the new selected value is different from the current value. Which makes sense to me as user interaction that doesn't actually change the value shouldn't typically trigger a change event.

```javascript
@Listen('MDCSelect:change')
handleInput(e: CustomEvent<MDCSelectEventDetail>) {
  e.preventDefault();
  const detailValue = e.detail?.value;

  if (detailValue !== this.value) { // here
    this.valueChange.emit(detailValue);
  }
}

``` 


Here is the code I used

Angular 12.0.1:

```html
<ino-select [value]="selectValue" (valueChange)="handleValueChange($event)">
  <ino-option value="Hamburg">Hamburg</ino-option>
  <ino-option value="Cologne">Cologne</ino-option>
</ino-select>
<button (click)="changeValueProgrammatically()">Change Value Programmatically</button>

``` 
```javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  selectValue: string = 'Hamburg';

  handleValueChange(event: any) {
    console.log('valueChange event:', event.detail);
  }
  

  changeValueProgrammatically() {
    this.selectValue = 'Cologne';
    console.log('Value programmatically changed to:', this.selectValue);
  }
}

``` 

React:

```javascript
import React, { useState, useEffect } from "react";
import { InoSelect, InoOption } from "@inovex.de/elements-react";
import "./App.css";

function App() {
  const [selectedValue, setSelectedValue] = useState("");

  useEffect(() => {
    console.log(`Render. Current value: ${selectedValue}`);
  });

  const handleChange = (event) => {
    console.log("User changed the value to:", event.detail);
    console.log("Event:", event); 
  };

  const handleClick = () => {
    const newValue = selectedValue === "Cologne" ? "Hamburg" : "Cologne";
    setSelectedValue(newValue);
    console.log(`Button clicked. Value programmatically changed to: ${newValue}`);
  };

  return (
    <div>
      <InoSelect
        label="Select label"
        value={selectedValue}
        onValueChange={handleChange}
      >
        <InoOption value="Cologne">Cologne</InoOption>
        <InoOption value="Hamburg">Hamburg</InoOption>
      </InoSelect>
      <button onClick={handleClick}>Change Value</button>
    </div>
  );
}

export default App;

```

**Comment by janivo** [comment]
I've tested it and can confirm that we currently cannot reproduce this bug. Thanks for the detailed write up @TobiasHeimGalindo 👍
