### ISSUE TITLE
Refactor footer design

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#998]
### Refactor Request

* Add aligned gaps between each navigation block
* Separate footer navigation above from legal footer below with a horizontal line or a background color to appear more separated to the rest of the page

<img width="1421" alt="elements_footer" src="https://github.com/inovex/elements/assets/1610894/1ca3d880-aa77-46ba-a5ad-35753b7dc76d">

**Comment by silentHoo** [comment]
As we use grid layout for aligning, the headline length leads to visual different column widths. A solution could be to add a background behind each headline.

We need design assistance here 😄

**Comment by TobiasHeimGalindo** [comment]
As we are still in the process of deciding on a suitable design for our footer, I've created 2 different variants (Preview Video in PR description below)

- Variant 1: #1049 
- Variant 2: #1053 

However the issue with the visual different column widths remains. Websites of Mercedes and Porsche use fixed-width columns with fixed gaps (like us). The abundance of their subcategories gives a visually aligned look. Our footer, with fewer subcategories (e.g., the Library category), appears inconsistent.

Mercedes Footer:

![Image](https://github.com/inovex/elements/assets/81302108/44f95fca-e76a-406f-88ad-c28c84f14a2b)

Variant 1: #1049 

![Image](https://github.com/inovex/elements/assets/81302108/159ca062-cade-48c9-8204-57ae6cf3ca15)

Variant 2: #1053 

![Image](https://github.com/inovex/elements/assets/81302108/53ceb61f-9764-41a1-8d7a-2b868e7ae6aa)
